### ISSUE TITLE
Doesn't Work in Glyphs V 2.2.2

### ISSUE THREAD

**Issue by Nevu** [mekkablue/ShowOffsetCurveParameterPreview#1]
Hi,

this nice Plugin doesn't work in version 2.2.2

I got the following message:

```
class GlyphsExpandPathsPreviewTool (NSObject, GlyphsReporter):
```

TypeError: Error when calling the metaclass bases
    class GlyphsExpandPathsPreviewTool does not fully implement protocol GlyphsToolEvent: no implementation for addMenuItemsForEvent:toMenu:

---

What I see, is a filled Glyph. 
When I haved used „Verfetten“ I see the dynamic changes in my Glyph.

but ...

When I haved used „Verfetten“ to save some Parameters (like for "Verfetten-Voschau"), nothing happened and I also just se a full filled glyph.

---

Do I use this plugin the right way?!

**Comment by mekkablue** [comment]
I just checked again and the plugin works fine in both 2.2.2 and 2.3. The error message ic not caused by the plugin. Please read the readme text for usage instructions.

You probably have an outdated Preview Offset plugin in your Plugins folder.
